import type { HandoverApiResponse } from "./contracts";

/**
 * Checked-in, fictional API responses for the portfolio demo.
 *
 * The values mirror the deterministic Task 2 comparison output for the
 * latest current snapshot and latest prior history snapshot of each patient.
 * They intentionally stay in the API's camelCase contract so the adapter can
 * be replaced by the endpoint without changing the workspace UI.
 */
export const DEMO_WORKSPACE_DATA: HandoverApiResponse[] = [
  {
    comparison: {
      patient: {
        id: "P001",
        name: "홍길동",
        room: "301",
        age: 67,
        sex: "M",
        diagnoses: ["acute pharyngitis", "hypertension"],
      },
      interval: {
        previousRecordedAt: "2026-07-02T07:00:00+09:00",
        currentRecordedAt: "2026-07-02T09:00:00+09:00",
      },
      status: "ready",
      dataWarnings: [],
      changes: [
        {
          id: "diagnosis-hypertension-97cf39b495a5-added",
          category: "diagnosis",
          changeType: "added",
          reviewPriority: "high",
          label: "hypertension",
          previousValue: null,
          currentValue: "hypertension",
          delta: null,
          evidence: {
            fieldPath: 'diagnosis["hypertension"]',
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "medications-타세놀정-500mg-3abed59ec690-added",
          category: "medications",
          changeType: "added",
          reviewPriority: "high",
          label: "타세놀정 500mg",
          previousValue: null,
          currentValue: {
            name: "타세놀정 500mg",
            route: "PO",
            frequency: "TID",
          },
          delta: null,
          evidence: {
            fieldPath: 'medications["타세놀정 500mg"]',
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "vitals-body_temperature-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "체온",
          previousValue: 37.9,
          currentValue: 38.2,
          delta: 0.3,
          evidence: {
            fieldPath: "vitals.body_temperature",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "vitals-diastolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "이완기 혈압",
          previousValue: 88,
          currentValue: 95,
          delta: 7,
          evidence: {
            fieldPath: "vitals.diastolic",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "vitals-heartrate-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "심박수",
          previousValue: 86,
          currentValue: 92,
          delta: 6,
          evidence: {
            fieldPath: "vitals.heartrate",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "vitals-respiratory-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "호흡수",
          previousValue: 17,
          currentValue: 18,
          delta: 1,
          evidence: {
            fieldPath: "vitals.respiratory",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "vitals-saturation-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "산소포화도",
          previousValue: 98,
          currentValue: 97,
          delta: -1,
          evidence: {
            fieldPath: "vitals.saturation",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "vitals-systolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "수축기 혈압",
          previousValue: 138,
          currentValue: 150,
          delta: 12,
          evidence: {
            fieldPath: "vitals.systolic",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
        {
          id: "notes-미열-지속-deb9221b78ad-added",
          category: "notes",
          changeType: "added",
          reviewPriority: "low",
          label: "미열 지속",
          previousValue: null,
          currentValue: "미열 지속",
          delta: null,
          evidence: {
            fieldPath: 'notes["미열 지속"]',
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:00:00+09:00",
          },
        },
      ],
    },
    summary: {
      mode: "deterministic",
      sections: {
        situation: [
          {
            text: "홍길동(P001) · 301호 · 07/02 07:00 → 09:00 · 변화 9건",
            evidenceIds: [
              "diagnosis-hypertension-97cf39b495a5-added",
              "medications-타세놀정-500mg-3abed59ec690-added",
              "vitals-body_temperature-modified",
              "vitals-diastolic-modified",
              "vitals-heartrate-modified",
              "vitals-respiratory-modified",
              "vitals-saturation-modified",
              "vitals-systolic-modified",
              "notes-미열-지속-deb9221b78ad-added",
            ],
          },
        ],
        background: [
          {
            text: "진단 추가: hypertension",
            evidenceIds: ["diagnosis-hypertension-97cf39b495a5-added"],
          },
          {
            text: "투약 추가: 타세놀정 500mg · PO · TID",
            evidenceIds: ["medications-타세놀정-500mg-3abed59ec690-added"],
          },
        ],
        assessment: [
          {
            text: "체온 변경: 37.9 -> 38.2",
            evidenceIds: ["vitals-body_temperature-modified"],
          },
          {
            text: "이완기 혈압 변경: 88 -> 95",
            evidenceIds: ["vitals-diastolic-modified"],
          },
          {
            text: "심박수 변경: 86 -> 92",
            evidenceIds: ["vitals-heartrate-modified"],
          },
          {
            text: "호흡수 변경: 17 -> 18",
            evidenceIds: ["vitals-respiratory-modified"],
          },
          {
            text: "산소포화도 변경: 98 -> 97",
            evidenceIds: ["vitals-saturation-modified"],
          },
          {
            text: "수축기 혈압 변경: 138 -> 150",
            evidenceIds: ["vitals-systolic-modified"],
          },
          {
            text: "간호 메모 추가: 미열 지속",
            evidenceIds: ["notes-미열-지속-deb9221b78ad-added"],
          },
        ],
        recommendation: [
          {
            text: "간호사가 확인할 후속 항목을 입력하세요.",
            evidenceIds: [],
          },
        ],
      },
      evidenceIds: [
        "diagnosis-hypertension-97cf39b495a5-added",
        "medications-타세놀정-500mg-3abed59ec690-added",
        "vitals-body_temperature-modified",
        "vitals-diastolic-modified",
        "vitals-heartrate-modified",
        "vitals-respiratory-modified",
        "vitals-saturation-modified",
        "vitals-systolic-modified",
        "notes-미열-지속-deb9221b78ad-added",
      ],
      warnings: [],
    },
  },
  {
    comparison: {
      patient: {
        id: "P002",
        name: "김영희",
        room: "302",
        age: 54,
        sex: "F",
        diagnoses: ["community acquired pneumonia"],
      },
      interval: {
        previousRecordedAt: "2026-07-02T06:00:00+09:00",
        currentRecordedAt: "2026-07-02T09:10:00+09:00",
      },
      status: "ready",
      dataWarnings: [],
      changes: [
        {
          id: "medications-아세틸시스테인-1363b9db6619-added",
          category: "medications",
          changeType: "added",
          reviewPriority: "high",
          label: "아세틸시스테인",
          previousValue: null,
          currentValue: {
            name: "아세틸시스테인",
            route: "NEB",
            frequency: "TID",
          },
          delta: null,
          evidence: {
            fieldPath: 'medications["아세틸시스테인"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
        {
          id: "vitals-body_temperature-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "체온",
          previousValue: 38.0,
          currentValue: 37.8,
          delta: -0.2,
          evidence: {
            fieldPath: "vitals.body_temperature",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
        {
          id: "vitals-diastolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "이완기 혈압",
          previousValue: 78,
          currentValue: 76,
          delta: -2,
          evidence: {
            fieldPath: "vitals.diastolic",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
        {
          id: "vitals-heartrate-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "심박수",
          previousValue: 92,
          currentValue: 88,
          delta: -4,
          evidence: {
            fieldPath: "vitals.heartrate",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
        {
          id: "vitals-respiratory-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "호흡수",
          previousValue: 23,
          currentValue: 22,
          delta: -1,
          evidence: {
            fieldPath: "vitals.respiratory",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
        {
          id: "vitals-saturation-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "산소포화도",
          previousValue: 91,
          currentValue: 92,
          delta: 1,
          evidence: {
            fieldPath: "vitals.saturation",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
        {
          id: "vitals-systolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "수축기 혈압",
          previousValue: 130,
          currentValue: 128,
          delta: -2,
          evidence: {
            fieldPath: "vitals.systolic",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
        {
          id: "notes-산소-유지-필요-6da9ac64a4c1-added",
          category: "notes",
          changeType: "added",
          reviewPriority: "low",
          label: "산소 유지 필요",
          previousValue: null,
          currentValue: "산소 유지 필요",
          delta: null,
          evidence: {
            fieldPath: 'notes["산소 유지 필요"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:10:00+09:00",
          },
        },
      ],
    },
    summary: {
      mode: "deterministic",
      sections: {
        situation: [
          {
            text: "김영희(P002) · 302호 · 07/02 06:00 → 09:10 · 변화 8건",
            evidenceIds: [
              "medications-아세틸시스테인-1363b9db6619-added",
              "vitals-body_temperature-modified",
              "vitals-diastolic-modified",
              "vitals-heartrate-modified",
              "vitals-respiratory-modified",
              "vitals-saturation-modified",
              "vitals-systolic-modified",
              "notes-산소-유지-필요-6da9ac64a4c1-added",
            ],
          },
        ],
        background: [
          {
            text: "투약 추가: 아세틸시스테인 · NEB · TID",
            evidenceIds: ["medications-아세틸시스테인-1363b9db6619-added"],
          },
        ],
        assessment: [
          {
            text: "체온 변경: 38.0 -> 37.8",
            evidenceIds: ["vitals-body_temperature-modified"],
          },
          {
            text: "이완기 혈압 변경: 78 -> 76",
            evidenceIds: ["vitals-diastolic-modified"],
          },
          {
            text: "심박수 변경: 92 -> 88",
            evidenceIds: ["vitals-heartrate-modified"],
          },
          {
            text: "호흡수 변경: 23 -> 22",
            evidenceIds: ["vitals-respiratory-modified"],
          },
          {
            text: "산소포화도 변경: 91 -> 92",
            evidenceIds: ["vitals-saturation-modified"],
          },
          {
            text: "수축기 혈압 변경: 130 -> 128",
            evidenceIds: ["vitals-systolic-modified"],
          },
          {
            text: "간호 메모 추가: 산소 유지 필요",
            evidenceIds: ["notes-산소-유지-필요-6da9ac64a4c1-added"],
          },
        ],
        recommendation: [
          {
            text: "간호사가 확인할 후속 항목을 입력하세요.",
            evidenceIds: [],
          },
        ],
      },
      evidenceIds: [
        "medications-아세틸시스테인-1363b9db6619-added",
        "vitals-body_temperature-modified",
        "vitals-diastolic-modified",
        "vitals-heartrate-modified",
        "vitals-respiratory-modified",
        "vitals-saturation-modified",
        "vitals-systolic-modified",
        "notes-산소-유지-필요-6da9ac64a4c1-added",
      ],
      warnings: [],
    },
  },
  {
    comparison: {
      patient: {
        id: "P003",
        name: "박민수",
        room: "401",
        age: 72,
        sex: "M",
        diagnoses: ["acute decompensated heart failure", "atrial fibrillation"],
      },
      interval: {
        previousRecordedAt: "2026-07-02T06:00:00+09:00",
        currentRecordedAt: "2026-07-02T09:20:00+09:00",
      },
      status: "ready",
      dataWarnings: [],
      changes: [
        {
          id: "diagnosis-atrial-fibrillation-09417dacb727-added",
          category: "diagnosis",
          changeType: "added",
          reviewPriority: "high",
          label: "atrial fibrillation",
          previousValue: null,
          currentValue: "atrial fibrillation",
          delta: null,
          evidence: {
            fieldPath: 'diagnosis["atrial fibrillation"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "medications-디곡신-0-125mg-7f4b9374bd0b-added",
          category: "medications",
          changeType: "added",
          reviewPriority: "high",
          label: "디곡신 0.125mg",
          previousValue: null,
          currentValue: {
            name: "디곡신 0.125mg",
            route: "PO",
            frequency: "QD",
          },
          delta: null,
          evidence: {
            fieldPath: 'medications["디곡신 0.125mg"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "vitals-diastolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "이완기 혈압",
          previousValue: 66,
          currentValue: 64,
          delta: -2,
          evidence: {
            fieldPath: "vitals.diastolic",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "vitals-heartrate-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "심박수",
          previousValue: 112,
          currentValue: 108,
          delta: -4,
          evidence: {
            fieldPath: "vitals.heartrate",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "vitals-respiratory-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "호흡수",
          previousValue: 22,
          currentValue: 20,
          delta: -2,
          evidence: {
            fieldPath: "vitals.respiratory",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "vitals-saturation-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "산소포화도",
          previousValue: 94,
          currentValue: 95,
          delta: 1,
          evidence: {
            fieldPath: "vitals.saturation",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "vitals-systolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "수축기 혈압",
          previousValue: 108,
          currentValue: 104,
          delta: -4,
          evidence: {
            fieldPath: "vitals.systolic",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "notes-소변량-증가-afc0b9ab3b91-removed",
          category: "notes",
          changeType: "removed",
          reviewPriority: "low",
          label: "소변량 증가",
          previousValue: "소변량 증가",
          currentValue: null,
          delta: null,
          evidence: {
            fieldPath: 'notes["소변량 증가"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
        {
          id: "notes-하지-부종-관찰-914e66cd45ba-added",
          category: "notes",
          changeType: "added",
          reviewPriority: "low",
          label: "하지 부종 관찰",
          previousValue: null,
          currentValue: "하지 부종 관찰",
          delta: null,
          evidence: {
            fieldPath: 'notes["하지 부종 관찰"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:20:00+09:00",
          },
        },
      ],
    },
    summary: {
      mode: "deterministic",
      sections: {
        situation: [
          {
            text: "박민수(P003) · 401호 · 07/02 06:00 → 09:20 · 변화 9건",
            evidenceIds: [
              "diagnosis-atrial-fibrillation-09417dacb727-added",
              "medications-디곡신-0-125mg-7f4b9374bd0b-added",
              "vitals-diastolic-modified",
              "vitals-heartrate-modified",
              "vitals-respiratory-modified",
              "vitals-saturation-modified",
              "vitals-systolic-modified",
              "notes-소변량-증가-afc0b9ab3b91-removed",
              "notes-하지-부종-관찰-914e66cd45ba-added",
            ],
          },
        ],
        background: [
          {
            text: "진단 추가: atrial fibrillation",
            evidenceIds: ["diagnosis-atrial-fibrillation-09417dacb727-added"],
          },
          {
            text: "투약 추가: 디곡신 0.125mg · PO · QD",
            evidenceIds: ["medications-디곡신-0-125mg-7f4b9374bd0b-added"],
          },
        ],
        assessment: [
          {
            text: "이완기 혈압 변경: 66 -> 64",
            evidenceIds: ["vitals-diastolic-modified"],
          },
          {
            text: "심박수 변경: 112 -> 108",
            evidenceIds: ["vitals-heartrate-modified"],
          },
          {
            text: "호흡수 변경: 22 -> 20",
            evidenceIds: ["vitals-respiratory-modified"],
          },
          {
            text: "산소포화도 변경: 94 -> 95",
            evidenceIds: ["vitals-saturation-modified"],
          },
          {
            text: "수축기 혈압 변경: 108 -> 104",
            evidenceIds: ["vitals-systolic-modified"],
          },
          {
            text: "간호 메모 삭제: 소변량 증가",
            evidenceIds: ["notes-소변량-증가-afc0b9ab3b91-removed"],
          },
          {
            text: "간호 메모 추가: 하지 부종 관찰",
            evidenceIds: ["notes-하지-부종-관찰-914e66cd45ba-added"],
          },
        ],
        recommendation: [
          {
            text: "간호사가 확인할 후속 항목을 입력하세요.",
            evidenceIds: [],
          },
        ],
      },
      evidenceIds: [
        "diagnosis-atrial-fibrillation-09417dacb727-added",
        "medications-디곡신-0-125mg-7f4b9374bd0b-added",
        "vitals-diastolic-modified",
        "vitals-heartrate-modified",
        "vitals-respiratory-modified",
        "vitals-saturation-modified",
        "vitals-systolic-modified",
        "notes-소변량-증가-afc0b9ab3b91-removed",
        "notes-하지-부종-관찰-914e66cd45ba-added",
      ],
      warnings: [],
    },
  },
  {
    comparison: {
      patient: {
        id: "P004",
        name: "최수진",
        room: "205",
        age: 38,
        sex: "F",
        diagnoses: ["post appendectomy"],
      },
      interval: {
        previousRecordedAt: "2026-07-02T06:00:00+09:00",
        currentRecordedAt: "2026-07-02T08:40:00+09:00",
      },
      status: "ready",
      dataWarnings: [],
      changes: [
        {
          id: "vitals-body_temperature-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "체온",
          previousValue: 36.8,
          currentValue: 36.5,
          delta: -0.3,
          evidence: {
            fieldPath: "vitals.body_temperature",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
        {
          id: "vitals-diastolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "이완기 혈압",
          previousValue: 74,
          currentValue: 72,
          delta: -2,
          evidence: {
            fieldPath: "vitals.diastolic",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
        {
          id: "vitals-heartrate-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "심박수",
          previousValue: 84,
          currentValue: 76,
          delta: -8,
          evidence: {
            fieldPath: "vitals.heartrate",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
        {
          id: "vitals-systolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "수축기 혈압",
          previousValue: 120,
          currentValue: 118,
          delta: -2,
          evidence: {
            fieldPath: "vitals.systolic",
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
        {
          id: "notes-보행-시작-af39bee34be0-added",
          category: "notes",
          changeType: "added",
          reviewPriority: "low",
          label: "보행 시작",
          previousValue: null,
          currentValue: "보행 시작",
          delta: null,
          evidence: {
            fieldPath: 'notes["보행 시작"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
        {
          id: "notes-복강경-수술-후-통증-감소-8f3d4da336b9-added",
          category: "notes",
          changeType: "added",
          reviewPriority: "low",
          label: "복강경 수술 후 통증 감소",
          previousValue: null,
          currentValue: "복강경 수술 후 통증 감소",
          delta: null,
          evidence: {
            fieldPath: 'notes["복강경 수술 후 통증 감소"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
        {
          id: "notes-침상-가장자리-앉기-시행-befeaeb9ae22-removed",
          category: "notes",
          changeType: "removed",
          reviewPriority: "low",
          label: "침상 가장자리 앉기 시행",
          previousValue: "침상 가장자리 앉기 시행",
          currentValue: null,
          delta: null,
          evidence: {
            fieldPath: 'notes["침상 가장자리 앉기 시행"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
        {
          id: "notes-통증-감소-7e6104a53708-removed",
          category: "notes",
          changeType: "removed",
          reviewPriority: "low",
          label: "통증 감소",
          previousValue: "통증 감소",
          currentValue: null,
          delta: null,
          evidence: {
            fieldPath: 'notes["통증 감소"]',
            previousRecordedAt: "2026-07-02T06:00:00+09:00",
            currentRecordedAt: "2026-07-02T08:40:00+09:00",
          },
        },
      ],
    },
    summary: {
      mode: "deterministic",
      sections: {
        situation: [
          {
            text: "최수진(P004) · 205호 · 07/02 06:00 → 08:40 · 변화 8건",
            evidenceIds: [
              "vitals-body_temperature-modified",
              "vitals-diastolic-modified",
              "vitals-heartrate-modified",
              "vitals-systolic-modified",
              "notes-보행-시작-af39bee34be0-added",
              "notes-복강경-수술-후-통증-감소-8f3d4da336b9-added",
              "notes-침상-가장자리-앉기-시행-befeaeb9ae22-removed",
              "notes-통증-감소-7e6104a53708-removed",
            ],
          },
        ],
        background: [],
        assessment: [
          {
            text: "체온 변경: 36.8 -> 36.5",
            evidenceIds: ["vitals-body_temperature-modified"],
          },
          {
            text: "이완기 혈압 변경: 74 -> 72",
            evidenceIds: ["vitals-diastolic-modified"],
          },
          {
            text: "심박수 변경: 84 -> 76",
            evidenceIds: ["vitals-heartrate-modified"],
          },
          {
            text: "수축기 혈압 변경: 120 -> 118",
            evidenceIds: ["vitals-systolic-modified"],
          },
          {
            text: "간호 메모 추가: 보행 시작",
            evidenceIds: ["notes-보행-시작-af39bee34be0-added"],
          },
          {
            text: "간호 메모 추가: 복강경 수술 후 통증 감소",
            evidenceIds: ["notes-복강경-수술-후-통증-감소-8f3d4da336b9-added"],
          },
          {
            text: "간호 메모 삭제: 침상 가장자리 앉기 시행",
            evidenceIds: ["notes-침상-가장자리-앉기-시행-befeaeb9ae22-removed"],
          },
          {
            text: "간호 메모 삭제: 통증 감소",
            evidenceIds: ["notes-통증-감소-7e6104a53708-removed"],
          },
        ],
        recommendation: [
          {
            text: "간호사가 확인할 후속 항목을 입력하세요.",
            evidenceIds: [],
          },
        ],
      },
      evidenceIds: [
        "vitals-body_temperature-modified",
        "vitals-diastolic-modified",
        "vitals-heartrate-modified",
        "vitals-systolic-modified",
        "notes-보행-시작-af39bee34be0-added",
        "notes-복강경-수술-후-통증-감소-8f3d4da336b9-added",
        "notes-침상-가장자리-앉기-시행-befeaeb9ae22-removed",
        "notes-통증-감소-7e6104a53708-removed",
      ],
      warnings: [],
    },
  },
  {
    comparison: {
      patient: {
        id: "P005",
        name: "이정호",
        room: "503",
        age: 61,
        sex: "M",
        diagnoses: ["type 2 diabetes mellitus", "right diabetic foot ulcer"],
      },
      interval: {
        previousRecordedAt: "2026-07-02T07:00:00+09:00",
        currentRecordedAt: "2026-07-02T09:30:00+09:00",
      },
      status: "ready",
      dataWarnings: [],
      changes: [
        {
          id: "vitals-body_temperature-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "체온",
          previousValue: 37.5,
          currentValue: 37.2,
          delta: -0.3,
          evidence: {
            fieldPath: "vitals.body_temperature",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:30:00+09:00",
          },
        },
        {
          id: "vitals-diastolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "이완기 혈압",
          previousValue: 86,
          currentValue: 84,
          delta: -2,
          evidence: {
            fieldPath: "vitals.diastolic",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:30:00+09:00",
          },
        },
        {
          id: "vitals-heartrate-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "심박수",
          previousValue: 84,
          currentValue: 82,
          delta: -2,
          evidence: {
            fieldPath: "vitals.heartrate",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:30:00+09:00",
          },
        },
        {
          id: "vitals-systolic-modified",
          category: "vitals",
          changeType: "modified",
          reviewPriority: "medium",
          label: "수축기 혈압",
          previousValue: 138,
          currentValue: 136,
          delta: -2,
          evidence: {
            fieldPath: "vitals.systolic",
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:30:00+09:00",
          },
        },
        {
          id: "notes-혈당-조절-필요-101efe23ac9f-added",
          category: "notes",
          changeType: "added",
          reviewPriority: "low",
          label: "혈당 조절 필요",
          previousValue: null,
          currentValue: "혈당 조절 필요",
          delta: null,
          evidence: {
            fieldPath: 'notes["혈당 조절 필요"]',
            previousRecordedAt: "2026-07-02T07:00:00+09:00",
            currentRecordedAt: "2026-07-02T09:30:00+09:00",
          },
        },
      ],
    },
    summary: {
      mode: "deterministic",
      sections: {
        situation: [
          {
            text: "이정호(P005) · 503호 · 07/02 07:00 → 09:30 · 변화 5건",
            evidenceIds: [
              "vitals-body_temperature-modified",
              "vitals-diastolic-modified",
              "vitals-heartrate-modified",
              "vitals-systolic-modified",
              "notes-혈당-조절-필요-101efe23ac9f-added",
            ],
          },
        ],
        background: [],
        assessment: [
          {
            text: "체온 변경: 37.5 -> 37.2",
            evidenceIds: ["vitals-body_temperature-modified"],
          },
          {
            text: "이완기 혈압 변경: 86 -> 84",
            evidenceIds: ["vitals-diastolic-modified"],
          },
          {
            text: "심박수 변경: 84 -> 82",
            evidenceIds: ["vitals-heartrate-modified"],
          },
          {
            text: "수축기 혈압 변경: 138 -> 136",
            evidenceIds: ["vitals-systolic-modified"],
          },
          {
            text: "간호 메모 추가: 혈당 조절 필요",
            evidenceIds: ["notes-혈당-조절-필요-101efe23ac9f-added"],
          },
        ],
        recommendation: [
          {
            text: "간호사가 확인할 후속 항목을 입력하세요.",
            evidenceIds: [],
          },
        ],
      },
      evidenceIds: [
        "vitals-body_temperature-modified",
        "vitals-diastolic-modified",
        "vitals-heartrate-modified",
        "vitals-systolic-modified",
        "notes-혈당-조절-필요-101efe23ac9f-added",
      ],
      warnings: [],
    },
  },
];

export const demoWorkspaceData = DEMO_WORKSPACE_DATA;
